#!/usr/bin/env bash
# Bash script that installs nginx, configures, and starts the server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R ubuntu /var/www
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
