#!/usr/bin/env bash
# Bash script that installs nginx, configures, and starts the server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
