#!/usr/bin/env bash
# Installs and configures Nginx on a new Ubuntu machine such that it:
#+    Listens on port 80.
#+    Includes a custom 404 page containing "Ceci n'est pas une page".
#+    Contains a custom HTTP response header named X-Served-By.
#+    The value of the HTTP header is the hostname of the running server

INDEX_COPY="Hello World!"
ERROR_COPY="Ceci n'est pas une page - 404"

sudo apt-get -y update
sudo apt-get -y install nginx

echo "$INDEX_COPY" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
echo "$ERROR_COPY" | sudo tee /var/www/html/custom_404.html > /dev/null

# Config redirection
sudo sed -i '/^\sserver_name.*/a \	rewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;' /etc/nginx/sites-available/default

# Config custom 404
sudo sed -i '/^\slocation.*/i \		error_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# shellcheck disable=SC2154
# Config custom HTTP response header
sudo sed -i '/^\slocation.*/i \		add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Run server
sudo service nginx start
