#!/usr/bin/env bash
#displays the content of the file /etc/passwd
#should only display: username, user id, and home directory path for the user
#must use the while loop (for and until are forbidden)

while read -r passwd
do
	echo "$passwd" | cut -d ':' -f 1,3,6
done < /etc/passwd
