#!/usr/bin/env bash
# Tells a story based on the contents of the `/etc/passwd` file
# displays the content of the file /etc/passwd, using the while loop + IFS
# f1:USERNAME f2:PASSWORD f3:USERID f4:GROUPID f5:UIF f6:HOME f7:COMMAND

while IFS=':' read -r f1 f2 f3 f4 f5 f6 f7
do
	echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3's place is protected by the passcode $f2, more info about the user here: $f5"
done < /etc/passwd
