#!/usr/bin/env bash
# Bash script that creates a RSA key pair with the following specifics:
# name of key: betty
# bits in the created key: 4096
# key must be protected by a passphrase
ssh-keygen -b 4096 -f betty -t rsa -P hello
